<!DOCTYPE html>
<html>
    <head>
        <title>Project</title>
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>
    <body>
    <div class="container">
        <div class="row">

            <div class="col-sm-8 col-sm-offset-2">

                <h2>Programming Task</h2> </br>
                <?php echo $this->fileUploadForm; ?>
            </div>

        </div>

     </div>
</body>
</html>